### ISSUE TITLE
Question about your Dockerfile

### ISSUE THREAD

**Issue by smutel** [robertdebock/docker-cntlm#9]
Hello,

In order to learn docker & more, I wanted to create my own dockerfile to launch cntlm.
So I created a dockerfile based on ubuntu, install cntlm from the repo.

When I try to start cntlm directly from CMD, it does not work:
`CMD ["/usr/sbin/cntlm", "-c /etc/cntlm.conf -f"]`
Docker is exiting immediately and docker logs returns:
> Exitting with error. Check daemon logs or run with -v.

When I use a bash script like your start.sh script and put this command in it, it works fine.
Do you know the reason of this behavior?

Thanks.

**Comment by robertdebock** [comment]
Hi,

You can use a [simpler syntax](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact) as such:

```
CMD /usr/sbin/cntlm -c /etc/cntlm.conf -f
```

That does not really explain why your command is not working, I suggest to [debug a little more](https://medium.com/@betz.mark/ten-tips-for-debugging-docker-containers-cde4da841a1d).

Regards,

Robert de Bock.
